// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    checkbox: string
    input: string
    label: string
    toggler: string
    wrapper: string
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss

export = StyleCssModule
